import type { Division, Fighter, Ratings, Sex, Stance } from "./types";

const BASE: Ratings = {
  stkOut: 55,
  stkAcc: 55,
  power: 55,
  stkDef: 55,
  kicks: 52,
  clinch: 52,
  tdOff: 50,
  tdDef: 55,
  chain: 50,
  top: 52,
  bottom: 50,
  gnp: 52,
  subOff: 48,
  subDef: 55,
  back: 50,
  cardio: 60,
  chin: 58,
  speed: 58,
  explode: 55,
  strength: 55,
  iq: 58,
  composure: 58,
  killer: 52,
  pace: 58,
};

type Input = {
  id: string;
  first: string;
  last: string;
  nickname?: string;
  division: Division;
  sex?: Sex;
  stance?: Stance;
  heightIn: number;
  reachIn: number;
  age: number;
  country: string;
  w: number;
  l: number;
  d?: number;
  nc?: number;
  ranking?: number | "C";
  koWins: number;
  subWins: number;
  decWins?: number;
  koLosses?: number;
  subLosses?: number;
  ratings: Partial<Ratings>;
  flags?: Fighter["flags"];
  notes?: string;
};

function isWomens(d: Division): boolean {
  return d.startsWith("womens-");
}

function make(p: Input): Fighter {
  const decWins = p.decWins ?? Math.max(0, p.w - p.koWins - p.subWins);
  return {
    id: p.id,
    first: p.first,
    last: p.last,
    nickname: p.nickname,
    division: p.division,
    sex: p.sex ?? (isWomens(p.division) ? "F" : "M"),
    stance: p.stance ?? "orthodox",
    heightIn: p.heightIn,
    reachIn: p.reachIn,
    age: p.age,
    country: p.country,
    record: { w: p.w, l: p.l, d: p.d ?? 0, nc: p.nc },
    ranking: p.ranking,
    koWins: p.koWins,
    subWins: p.subWins,
    decWins,
    koLosses: p.koLosses ?? 0,
    subLosses: p.subLosses ?? 0,
    ratings: { ...BASE, ...p.ratings },
    flags: p.flags,
    notes: p.notes,
  };
}

/** Ratings are 2026 form, not career peaks. 50 = UFC replacement level. */
export const FIGHTERS: Fighter[] = [
  make({
    id: "natalia-silva",
    first: "Natalia",
    last: "Silva",
    division: "womens-flyweight",
    stance: "southpaw",
    heightIn: 64,
    reachIn: 65,
    age: 29,
    country: "Brazil",
    w: 20,
    l: 5,
    d: 1,
    ranking: 1,
    koWins: 8,
    subWins: 2,
    ratings: {
      stkOut: 78, stkAcc: 74, power: 62, stkDef: 76, kicks: 82, clinch: 68,
      tdOff: 48, tdDef: 64, chain: 50, top: 58, bottom: 56, gnp: 58,
      subOff: 50, subDef: 66, back: 52,
      cardio: 80, chin: 70, speed: 76, explode: 70, strength: 58,
      iq: 84, composure: 82, killer: 64, pace: 72,
    },
    flags: { southpawKicker: true, counterStriker: true },
    notes: "14-fight run. Real southpaw kickboxing, not a volume illusion. Wrestling is the question she hasn't been forced to answer at title depth.",
  }),
  make({
    id: "wang-cong",
    first: "Wang",
    last: "Cong",
    division: "womens-flyweight",
    stance: "southpaw",
    heightIn: 66,
    reachIn: 65.5,
    age: 34,
    country: "China",
    w: 10,
    l: 1,
    ranking: 8,
    koWins: 5,
    subWins: 2,
    ratings: {
      stkOut: 86, stkAcc: 80, power: 70, stkDef: 66, kicks: 88, clinch: 60,
      tdOff: 54, tdDef: 52, chain: 48, top: 50, bottom: 48, gnp: 54,
      subOff: 54, subDef: 50, back: 50,
      cardio: 66, chin: 64, speed: 74, explode: 72, strength: 64,
      iq: 70, composure: 66, killer: 70, pace: 82,
    },
    flags: { southpawKicker: true, calfKicker: true },
    notes: "Kickboxing sample is loud. MMA sample is short. 34 at altitude over five is the hidden tax.",
  }),
  make({
    id: "payton-talbott",
    first: "Payton",
    last: "Talbott",
    division: "bantamweight",
    heightIn: 70,
    reachIn: 71.5,
    age: 27,
    country: "USA",
    w: 11,
    l: 1,
    ranking: 12,
    koWins: 8,
    subWins: 1,
    ratings: {
      stkOut: 80, stkAcc: 72, power: 80, stkDef: 70, kicks: 68, clinch: 58,
      tdOff: 48, tdDef: 70, chain: 46, top: 52, bottom: 48, gnp: 62,
      subOff: 48, subDef: 62, back: 48,
      cardio: 74, chin: 68, speed: 86, explode: 84, strength: 64,
      iq: 68, composure: 66, killer: 78, pace: 76,
    },
    flags: { oneHitter: true },
  }),
  make({
    id: "deiveson-figueiredo",
    first: "Deiveson",
    last: "Figueiredo",
    nickname: "Deus da Guerra",
    division: "bantamweight",
    heightIn: 65,
    reachIn: 68,
    age: 38,
    country: "Brazil",
    w: 25,
    l: 7,
    d: 1,
    ranking: 9,
    koWins: 9,
    subWins: 9,
    koLosses: 3,
    subLosses: 1,
    ratings: {
      stkOut: 62, stkAcc: 64, power: 88, stkDef: 52, kicks: 50, clinch: 70,
      tdOff: 72, tdDef: 58, chain: 68, top: 74, bottom: 70, gnp: 78,
      subOff: 86, subDef: 72, back: 80,
      cardio: 58, chin: 48, speed: 62, explode: 68, strength: 78,
      iq: 72, composure: 64, killer: 86, pace: 64,
    },
    flags: { oneHitter: true },
    notes: "Former two-division champion walking into 135 with a weathered chin and a still-vicious finishing toolkit. The name is the trap; the power is not imaginary.",
  }),
  make({
    id: "king-green",
    first: "Bobby",
    last: "Green",
    nickname: "King",
    division: "lightweight",
    stance: "southpaw",
    heightIn: 70,
    reachIn: 71.5,
    age: 40,
    country: "USA",
    w: 36,
    l: 17,
    d: 1,
    koWins: 10,
    subWins: 8,
    koLosses: 5,
    ratings: {
      stkOut: 72, stkAcc: 62, power: 64, stkDef: 58, kicks: 55, clinch: 68,
      tdOff: 58, tdDef: 60, chain: 56, top: 62, bottom: 64, gnp: 60,
      subOff: 72, subDef: 66, back: 70,
      cardio: 70, chin: 52, speed: 66, explode: 58, strength: 62,
      iq: 78, composure: 60, killer: 68, pace: 74,
    },
    flags: { counterStriker: true },
    notes: "Chaos tax. Always live, always leaky. Age 40 is not a meme — the chin has receipts.",
  }),
  make({
    id: "esteban-ribovics",
    first: "Esteban",
    last: "Ribovics",
    division: "lightweight",
    heightIn: 70,
    reachIn: 72,
    age: 28,
    country: "Argentina",
    w: 16,
    l: 3,
    koWins: 10,
    subWins: 1,
    koLosses: 1,
    ratings: {
      stkOut: 78, stkAcc: 74, power: 76, stkDef: 68, kicks: 80, clinch: 54,
      tdOff: 42, tdDef: 62, chain: 40, top: 48, bottom: 46, gnp: 58,
      subOff: 40, subDef: 54, back: 42,
      cardio: 72, chin: 64, speed: 74, explode: 72, strength: 60,
      iq: 66, composure: 64, killer: 74, pace: 74,
    },
    flags: { calfKicker: true },
  }),
  make({
    id: "roberto-soldic",
    first: "Roberto",
    last: "Soldić",
    nickname: "Robocop",
    division: "welterweight",
    stance: "southpaw",
    heightIn: 71,
    reachIn: 73,
    age: 31,
    country: "Croatia",
    w: 21,
    l: 4,
    koWins: 17,
    subWins: 0,
    koLosses: 3,
    ratings: {
      stkOut: 70, stkAcc: 72, power: 90, stkDef: 60, kicks: 64, clinch: 58,
      tdOff: 48, tdDef: 58, chain: 44, top: 50, bottom: 46, gnp: 66,
      subOff: 36, subDef: 52, back: 40,
      cardio: 64, chin: 62, speed: 70, explode: 78, strength: 72,
      iq: 62, composure: 58, killer: 88, pace: 70,
    },
    flags: { ufcDebut: true, oneHitter: true },
    notes: "KSW wrecking ball. UFC debut. Power is real; cage craft against a long athletic wildman is the unknown.",
  }),
  make({
    id: "khaos-williams",
    first: "Khaos",
    last: "Williams",
    division: "welterweight",
    heightIn: 72,
    reachIn: 77,
    age: 32,
    country: "USA",
    w: 16,
    l: 5,
    koWins: 12,
    subWins: 0,
    koLosses: 2,
    ratings: {
      stkOut: 68, stkAcc: 62, power: 86, stkDef: 50, kicks: 58, clinch: 52,
      tdOff: 40, tdDef: 54, chain: 38, top: 44, bottom: 42, gnp: 60,
      subOff: 32, subDef: 48, back: 36,
      cardio: 62, chin: 66, speed: 74, explode: 82, strength: 70,
      iq: 52, composure: 50, killer: 80, pace: 72,
    },
    flags: { oneHitter: true },
  }),
  make({
    id: "ateba-gautier",
    first: "Ateba",
    last: "Gautier",
    division: "middleweight",
    heightIn: 75,
    reachIn: 78,
    age: 25,
    country: "Cameroon",
    w: 11,
    l: 1,
    koWins: 8,
    subWins: 1,
    ratings: {
      stkOut: 72, stkAcc: 68, power: 78, stkDef: 62, kicks: 66, clinch: 60,
      tdOff: 58, tdDef: 60, chain: 54, top: 58, bottom: 50, gnp: 70,
      subOff: 52, subDef: 56, back: 52,
      cardio: 70, chin: 66, speed: 74, explode: 80, strength: 72,
      iq: 60, composure: 58, killer: 76, pace: 74,
    },
  }),
  make({
    id: "roman-kopylov",
    first: "Roman",
    last: "Kopylov",
    division: "middleweight",
    stance: "southpaw",
    heightIn: 72,
    reachIn: 75,
    age: 31,
    country: "Russia",
    w: 15,
    l: 5,
    koWins: 10,
    subWins: 0,
    koLosses: 1,
    ratings: {
      stkOut: 70, stkAcc: 72, power: 82, stkDef: 64, kicks: 86, clinch: 50,
      tdOff: 38, tdDef: 58, chain: 36, top: 44, bottom: 42, gnp: 54,
      subOff: 34, subDef: 52, back: 36,
      cardio: 64, chin: 62, speed: 68, explode: 70, strength: 66,
      iq: 64, composure: 60, killer: 78, pace: 66,
    },
    flags: { bodyAttacker: true, southpawKicker: true },
    notes: "Body-kick KO artist. Can be outworked if the fight is a wrestling meet.",
  }),
  make({
    id: "imanol-rodriguez",
    first: "Imanol",
    last: "Rodriguez",
    division: "flyweight",
    heightIn: 66,
    reachIn: 67,
    age: 26,
    country: "Mexico",
    w: 7,
    l: 0,
    koWins: 3,
    subWins: 2,
    ratings: {
      stkOut: 64, stkAcc: 62, power: 60, stkDef: 60, kicks: 58, clinch: 58,
      tdOff: 62, tdDef: 60, chain: 60, top: 62, bottom: 58, gnp: 60,
      subOff: 60, subDef: 58, back: 58,
      cardio: 68, chin: 62, speed: 66, explode: 64, strength: 58,
      iq: 60, composure: 60, killer: 58, pace: 66,
    },
  }),
  make({
    id: "alden-coria",
    first: "Alden",
    last: "Coria",
    division: "flyweight",
    heightIn: 65,
    reachIn: 66,
    age: 29,
    country: "USA",
    w: 13,
    l: 3,
    koWins: 4,
    subWins: 5,
    ratings: {
      stkOut: 58, stkAcc: 58, power: 54, stkDef: 58, kicks: 52, clinch: 60,
      tdOff: 66, tdDef: 58, chain: 64, top: 66, bottom: 62, gnp: 62,
      subOff: 68, subDef: 60, back: 66,
      cardio: 66, chin: 60, speed: 62, explode: 60, strength: 58,
      iq: 62, composure: 60, killer: 62, pace: 64,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "damian-pinas",
    first: "Damian",
    last: "Pinas",
    division: "middleweight",
    heightIn: 74,
    reachIn: 76,
    age: 27,
    country: "Suriname",
    w: 10,
    l: 1,
    koWins: 6,
    subWins: 2,
    ratings: {
      stkOut: 66, stkAcc: 64, power: 72, stkDef: 58, kicks: 60, clinch: 56,
      tdOff: 54, tdDef: 56, chain: 50, top: 54, bottom: 50, gnp: 64,
      subOff: 52, subDef: 54, back: 50,
      cardio: 64, chin: 62, speed: 66, explode: 70, strength: 70,
      iq: 56, composure: 56, killer: 68, pace: 66,
    },
  }),
  make({
    id: "andrey-pulyaev",
    first: "Andrey",
    last: "Pulyaev",
    division: "middleweight",
    heightIn: 73,
    reachIn: 74,
    age: 30,
    country: "Russia",
    w: 10,
    l: 5,
    koWins: 5,
    subWins: 2,
    koLosses: 2,
    ratings: {
      stkOut: 60, stkAcc: 58, power: 62, stkDef: 54, kicks: 56, clinch: 54,
      tdOff: 52, tdDef: 52, chain: 50, top: 52, bottom: 50, gnp: 56,
      subOff: 50, subDef: 52, back: 50,
      cardio: 58, chin: 54, speed: 58, explode: 58, strength: 62,
      iq: 54, composure: 52, killer: 56, pace: 58,
    },
  }),
  make({
    id: "marcus-mcghee",
    first: "Marcus",
    last: "McGhee",
    division: "featherweight",
    heightIn: 68,
    reachIn: 70,
    age: 30,
    country: "USA",
    w: 11,
    l: 2,
    ranking: 15,
    koWins: 7,
    subWins: 1,
    ratings: {
      stkOut: 74, stkAcc: 70, power: 72, stkDef: 66, kicks: 64, clinch: 56,
      tdOff: 48, tdDef: 64, chain: 46, top: 52, bottom: 48, gnp: 60,
      subOff: 44, subDef: 58, back: 46,
      cardio: 70, chin: 64, speed: 72, explode: 70, strength: 60,
      iq: 64, composure: 62, killer: 70, pace: 72,
    },
  }),
  make({
    id: "anthony-romero",
    first: "Anthony",
    last: "Romero",
    division: "featherweight",
    heightIn: 69,
    reachIn: 70,
    age: 27,
    country: "USA",
    w: 7,
    l: 2,
    koWins: 4,
    subWins: 1,
    koLosses: 1,
    ratings: {
      stkOut: 62, stkAcc: 60, power: 64, stkDef: 56, kicks: 58, clinch: 52,
      tdOff: 50, tdDef: 54, chain: 48, top: 50, bottom: 48, gnp: 56,
      subOff: 46, subDef: 52, back: 46,
      cardio: 62, chin: 56, speed: 64, explode: 64, strength: 56,
      iq: 54, composure: 52, killer: 58, pace: 62,
    },
  }),
  make({
    id: "anthony-wint",
    first: "Anthony",
    last: "Wint",
    division: "heavyweight",
    heightIn: 75,
    reachIn: 78,
    age: 28,
    country: "USA",
    w: 8,
    l: 0,
    koWins: 5,
    subWins: 2,
    ratings: {
      stkOut: 60, stkAcc: 58, power: 70, stkDef: 54, kicks: 48, clinch: 58,
      tdOff: 64, tdDef: 58, chain: 62, top: 64, bottom: 54, gnp: 66,
      subOff: 58, subDef: 56, back: 56,
      cardio: 56, chin: 62, speed: 54, explode: 62, strength: 74,
      iq: 56, composure: 56, killer: 64, pace: 58,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "lucas-armand",
    first: "Lucas",
    last: "Armand",
    division: "heavyweight",
    heightIn: 76,
    reachIn: 79,
    age: 27,
    country: "France",
    w: 6,
    l: 0,
    koWins: 4,
    subWins: 1,
    ratings: {
      stkOut: 58, stkAcc: 56, power: 68, stkDef: 52, kicks: 50, clinch: 54,
      tdOff: 52, tdDef: 52, chain: 48, top: 52, bottom: 48, gnp: 60,
      subOff: 48, subDef: 50, back: 46,
      cardio: 52, chin: 58, speed: 52, explode: 60, strength: 70,
      iq: 52, composure: 52, killer: 62, pace: 56,
    },
  }),
  make({
    id: "johnny-walker",
    first: "Johnny",
    last: "Walker",
    division: "heavyweight",
    heightIn: 78,
    reachIn: 82,
    age: 34,
    country: "Brazil",
    w: 22,
    l: 10,
    ranking: 13,
    koWins: 16,
    subWins: 3,
    koLosses: 6,
    ratings: {
      stkOut: 64, stkAcc: 58, power: 84, stkDef: 48, kicks: 72, clinch: 56,
      tdOff: 44, tdDef: 50, chain: 40, top: 48, bottom: 44, gnp: 62,
      subOff: 50, subDef: 50, back: 48,
      cardio: 52, chin: 50, speed: 68, explode: 76, strength: 72,
      iq: 48, composure: 44, killer: 74, pace: 66,
    },
    flags: { oneHitter: true },
    notes: "High-variance athlete. Chin and IQ have been the leaks for years. Altitude HW is a coin with a fuse.",
  }),
  make({
    id: "mick-parkin",
    first: "Mick",
    last: "Parkin",
    division: "heavyweight",
    heightIn: 76,
    reachIn: 77,
    age: 29,
    country: "England",
    w: 10,
    l: 1,
    koWins: 4,
    subWins: 2,
    ratings: {
      stkOut: 60, stkAcc: 62, power: 64, stkDef: 60, kicks: 54, clinch: 62,
      tdOff: 70, tdDef: 66, chain: 68, top: 68, bottom: 58, gnp: 66,
      subOff: 54, subDef: 60, back: 52,
      cardio: 64, chin: 68, speed: 54, explode: 58, strength: 76,
      iq: 64, composure: 66, killer: 58, pace: 60,
    },
    flags: { pressureWrestler: true },
    notes: "The boring correct heavyweight. Wrestling, durability, fewer leaks.",
  }),
  make({
    id: "rafael-dos-anjos",
    first: "Rafael",
    last: "dos Anjos",
    nickname: "RDA",
    division: "lightweight",
    stance: "southpaw",
    heightIn: 68,
    reachIn: 70,
    age: 42,
    country: "Brazil",
    w: 32,
    l: 17,
    koWins: 5,
    subWins: 10,
    ratings: {
      stkOut: 64, stkAcc: 68, power: 58, stkDef: 66, kicks: 70, clinch: 72,
      tdOff: 70, tdDef: 68, chain: 68, top: 74, bottom: 70, gnp: 66,
      subOff: 74, subDef: 72, back: 70,
      cardio: 62, chin: 64, speed: 52, explode: 50, strength: 66,
      iq: 86, composure: 80, killer: 62, pace: 66,
    },
    flags: { pressureWrestler: true, bodyAttacker: true },
    notes: "Former champion at 42. The IQ is still elite. The legs are not. Altitude is unkind.",
  }),
  make({
    id: "alexander-hernandez",
    first: "Alexander",
    last: "Hernandez",
    nickname: "The Great",
    division: "lightweight",
    heightIn: 69,
    reachIn: 72,
    age: 34,
    country: "USA",
    w: 18,
    l: 9,
    koWins: 8,
    subWins: 2,
    koLosses: 4,
    ratings: {
      stkOut: 70, stkAcc: 62, power: 70, stkDef: 58, kicks: 56, clinch: 54,
      tdOff: 58, tdDef: 56, chain: 54, top: 56, bottom: 50, gnp: 60,
      subOff: 44, subDef: 54, back: 46,
      cardio: 66, chin: 58, speed: 74, explode: 76, strength: 64,
      iq: 58, composure: 54, killer: 66, pace: 74,
    },
  }),
  make({
    id: "marvin-vettori",
    first: "Marvin",
    last: "Vettori",
    nickname: "The Italian Dream",
    division: "middleweight",
    stance: "southpaw",
    heightIn: 72,
    reachIn: 74,
    age: 33,
    country: "Italy",
    w: 19,
    l: 10,
    d: 1,
    koWins: 2,
    subWins: 4,
    ratings: {
      stkOut: 68, stkAcc: 58, power: 52, stkDef: 60, kicks: 54, clinch: 70,
      tdOff: 68, tdDef: 64, chain: 66, top: 70, bottom: 62, gnp: 64,
      subOff: 58, subDef: 64, back: 56,
      cardio: 74, chin: 78, speed: 54, explode: 52, strength: 70,
      iq: 66, composure: 70, killer: 48, pace: 76,
    },
    flags: { pressureWrestler: true, decisionWrestler: true },
  }),
  make({
    id: "ismail-naurdiev",
    first: "Ismail",
    last: "Naurdiev",
    division: "middleweight",
    heightIn: 72,
    reachIn: 74,
    age: 29,
    country: "Austria",
    w: 25,
    l: 8,
    koWins: 8,
    subWins: 6,
    ratings: {
      stkOut: 70, stkAcc: 66, power: 66, stkDef: 64, kicks: 64, clinch: 62,
      tdOff: 64, tdDef: 66, chain: 62, top: 64, bottom: 60, gnp: 64,
      subOff: 62, subDef: 62, back: 60,
      cardio: 70, chin: 66, speed: 66, explode: 64, strength: 66,
      iq: 66, composure: 64, killer: 62, pace: 68,
    },
  }),
  make({
    id: "jacobe-smith",
    first: "Jacobe",
    last: "Smith",
    division: "welterweight",
    heightIn: 72,
    reachIn: 74,
    age: 26,
    country: "USA",
    w: 12,
    l: 0,
    koWins: 6,
    subWins: 3,
    ratings: {
      stkOut: 68, stkAcc: 66, power: 70, stkDef: 64, kicks: 60, clinch: 60,
      tdOff: 66, tdDef: 64, chain: 64, top: 66, bottom: 58, gnp: 66,
      subOff: 60, subDef: 60, back: 58,
      cardio: 70, chin: 66, speed: 68, explode: 70, strength: 68,
      iq: 62, composure: 62, killer: 68, pace: 70,
    },
  }),
  make({
    id: "bruce-whitehead",
    first: "Bruce",
    last: "Whitehead",
    division: "welterweight",
    heightIn: 71,
    reachIn: 73,
    age: 30,
    country: "USA",
    w: 8,
    l: 2,
    koWins: 4,
    subWins: 1,
    koLosses: 1,
    ratings: {
      stkOut: 58, stkAcc: 56, power: 58, stkDef: 52, kicks: 52, clinch: 50,
      tdOff: 50, tdDef: 50, chain: 48, top: 50, bottom: 48, gnp: 54,
      subOff: 46, subDef: 50, back: 44,
      cardio: 56, chin: 54, speed: 58, explode: 58, strength: 56,
      iq: 52, composure: 50, killer: 54, pace: 56,
    },
  }),
  make({
    id: "court-mcgee",
    first: "Court",
    last: "McGee",
    nickname: "The Crusher",
    division: "welterweight",
    heightIn: 71,
    reachIn: 75,
    age: 41,
    country: "USA",
    w: 23,
    l: 14,
    koWins: 8,
    subWins: 6,
    ratings: {
      stkOut: 58, stkAcc: 56, power: 50, stkDef: 56, kicks: 48, clinch: 60,
      tdOff: 62, tdDef: 58, chain: 60, top: 64, bottom: 60, gnp: 58,
      subOff: 60, subDef: 62, back: 58,
      cardio: 68, chin: 70, speed: 46, explode: 44, strength: 62,
      iq: 70, composure: 74, killer: 48, pace: 62,
    },
    flags: { decisionWrestler: true },
  }),
  make({
    id: "eric-nolan",
    first: "Eric",
    last: "Nolan",
    division: "welterweight",
    heightIn: 72,
    reachIn: 74,
    age: 28,
    country: "USA",
    w: 8,
    l: 5,
    koWins: 5,
    subWins: 1,
    koLosses: 2,
    ratings: {
      stkOut: 64, stkAcc: 60, power: 66, stkDef: 56, kicks: 54, clinch: 52,
      tdOff: 48, tdDef: 54, chain: 46, top: 50, bottom: 46, gnp: 58,
      subOff: 44, subDef: 52, back: 44,
      cardio: 60, chin: 56, speed: 64, explode: 64, strength: 60,
      iq: 54, composure: 52, killer: 60, pace: 64,
    },
  }),
  make({
    id: "alexander-volkanovski",
    first: "Alexander",
    last: "Volkanovski",
    nickname: "The Great",
    division: "featherweight",
    heightIn: 66,
    reachIn: 71.5,
    age: 38,
    country: "Australia",
    w: 28,
    l: 4,
    ranking: "C",
    koWins: 13,
    subWins: 3,
    koLosses: 2,
    ratings: {
      stkOut: 86, stkAcc: 78, power: 72, stkDef: 80, kicks: 76, clinch: 78,
      tdOff: 74, tdDef: 84, chain: 76, top: 76, bottom: 70, gnp: 74,
      subOff: 60, subDef: 78, back: 62,
      cardio: 78, chin: 70, speed: 72, explode: 70, strength: 78,
      iq: 94, composure: 90, killer: 76, pace: 86,
    },
    flags: { pressureWrestler: true, bodyAttacker: true },
    notes: "Championship IQ still elite. 38 is 38. The 2019 cardio is not guaranteed in 2026 against a 20-0 wrestler who never gives a round back.",
  }),
  make({
    id: "movsar-evloev",
    first: "Movsar",
    last: "Evloev",
    division: "featherweight",
    heightIn: 67,
    reachIn: 72.5,
    age: 32,
    country: "Russia",
    w: 20,
    l: 0,
    ranking: 1,
    koWins: 3,
    subWins: 2,
    ratings: {
      stkOut: 72, stkAcc: 70, power: 58, stkDef: 76, kicks: 62, clinch: 80,
      tdOff: 88, tdDef: 86, chain: 90, top: 90, bottom: 72, gnp: 70,
      subOff: 62, subDef: 80, back: 70,
      cardio: 88, chin: 78, speed: 70, explode: 74, strength: 76,
      iq: 86, composure: 88, killer: 48, pace: 80,
    },
    flags: { pressureWrestler: true, decisionWrestler: true },
    notes: "20-0. Almost never finishes. The market always overprices his KO/SUB and underprices the wrestling tax he puts on strikers. Volk is not a striker.",
  }),
  make({
    id: "petr-yan",
    first: "Petr",
    last: "Yan",
    nickname: "No Mercy",
    division: "bantamweight",
    stance: "switch",
    heightIn: 67,
    reachIn: 67,
    age: 33,
    country: "Russia",
    w: 20,
    l: 5,
    ranking: "C",
    koWins: 8,
    subWins: 1,
    ratings: {
      stkOut: 84, stkAcc: 80, power: 76, stkDef: 82, kicks: 80, clinch: 74,
      tdOff: 62, tdDef: 78, chain: 64, top: 70, bottom: 66, gnp: 76,
      subOff: 50, subDef: 70, back: 52,
      cardio: 80, chin: 74, speed: 80, explode: 76, strength: 72,
      iq: 86, composure: 82, killer: 74, pace: 78,
    },
    flags: { calfKicker: true, counterStriker: true },
  }),
  make({
    id: "merab-dvalishvili",
    first: "Merab",
    last: "Dvalishvili",
    nickname: "The Machine",
    division: "bantamweight",
    heightIn: 66,
    reachIn: 68,
    age: 35,
    country: "Georgia",
    w: 21,
    l: 5,
    ranking: 1,
    koWins: 3,
    subWins: 2,
    ratings: {
      stkOut: 76, stkAcc: 58, power: 48, stkDef: 62, kicks: 50, clinch: 78,
      tdOff: 92, tdDef: 80, chain: 94, top: 86, bottom: 70, gnp: 64,
      subOff: 54, subDef: 72, back: 60,
      cardio: 96, chin: 80, speed: 74, explode: 78, strength: 74,
      iq: 78, composure: 86, killer: 44, pace: 98,
    },
    flags: { pressureWrestler: true, decisionWrestler: true },
    notes: "Pace is the weapon. Finishes are the lie the public keeps buying.",
  }),
  make({
    id: "loneer-kavanagh",
    first: "Lone'er",
    last: "Kavanagh",
    division: "flyweight",
    heightIn: 66,
    reachIn: 68,
    age: 26,
    country: "England",
    w: 10,
    l: 2,
    ranking: 6,
    koWins: 5,
    subWins: 1,
    koLosses: 1,
    ratings: {
      stkOut: 74, stkAcc: 70, power: 68, stkDef: 66, kicks: 68, clinch: 54,
      tdOff: 48, tdDef: 62, chain: 46, top: 50, bottom: 48, gnp: 58,
      subOff: 44, subDef: 56, back: 44,
      cardio: 70, chin: 62, speed: 76, explode: 74, strength: 56,
      iq: 64, composure: 60, killer: 66, pace: 72,
    },
  }),
  make({
    id: "ramazan-temirov",
    first: "Ramazan",
    last: "Temirov",
    division: "flyweight",
    heightIn: 65,
    reachIn: 66,
    age: 30,
    country: "Russia",
    w: 20,
    l: 3,
    ranking: 10,
    koWins: 6,
    subWins: 8,
    ratings: {
      stkOut: 62, stkAcc: 62, power: 58, stkDef: 64, kicks: 54, clinch: 66,
      tdOff: 74, tdDef: 70, chain: 74, top: 76, bottom: 68, gnp: 66,
      subOff: 76, subDef: 70, back: 74,
      cardio: 76, chin: 68, speed: 66, explode: 68, strength: 66,
      iq: 70, composure: 70, killer: 64, pace: 70,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "alexander-volkov",
    first: "Alexander",
    last: "Volkov",
    nickname: "Drago",
    division: "heavyweight",
    heightIn: 79,
    reachIn: 81.5,
    age: 38,
    country: "Russia",
    w: 40,
    l: 11,
    ranking: 2,
    koWins: 27,
    subWins: 3,
    koLosses: 5,
    ratings: {
      stkOut: 76, stkAcc: 72, power: 78, stkDef: 70, kicks: 80, clinch: 62,
      tdOff: 40, tdDef: 68, chain: 38, top: 52, bottom: 48, gnp: 64,
      subOff: 44, subDef: 62, back: 42,
      cardio: 68, chin: 66, speed: 58, explode: 58, strength: 74,
      iq: 78, composure: 76, killer: 70, pace: 64,
    },
  }),
  make({
    id: "rizvan-kuniev",
    first: "Rizvan",
    last: "Kuniev",
    division: "heavyweight",
    heightIn: 75,
    reachIn: 77,
    age: 33,
    country: "Russia",
    w: 14,
    l: 3,
    d: 1,
    ranking: 7,
    koWins: 8,
    subWins: 3,
    koLosses: 1,
    ratings: {
      stkOut: 64, stkAcc: 62, power: 72, stkDef: 60, kicks: 56, clinch: 64,
      tdOff: 70, tdDef: 64, chain: 68, top: 70, bottom: 58, gnp: 70,
      subOff: 60, subDef: 60, back: 58,
      cardio: 60, chin: 64, speed: 56, explode: 64, strength: 80,
      iq: 62, composure: 60, killer: 66, pace: 62,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "arnold-allen",
    first: "Arnold",
    last: "Allen",
    nickname: "Almighty",
    division: "featherweight",
    stance: "southpaw",
    heightIn: 69,
    reachIn: 70,
    age: 32,
    country: "England",
    w: 21,
    l: 4,
    ranking: 7,
    koWins: 7,
    subWins: 4,
    koLosses: 1,
    ratings: {
      stkOut: 74, stkAcc: 72, power: 70, stkDef: 74, kicks: 72, clinch: 66,
      tdOff: 62, tdDef: 72, chain: 60, top: 64, bottom: 62, gnp: 64,
      subOff: 62, subDef: 68, back: 60,
      cardio: 74, chin: 70, speed: 74, explode: 72, strength: 64,
      iq: 76, composure: 74, killer: 68, pace: 70,
    },
    flags: { counterStriker: true },
  }),
  make({
    id: "aaron-pico",
    first: "Aaron",
    last: "Pico",
    division: "featherweight",
    heightIn: 68,
    reachIn: 70,
    age: 30,
    country: "USA",
    w: 14,
    l: 5,
    ranking: 11,
    koWins: 8,
    subWins: 3,
    koLosses: 4,
    ratings: {
      stkOut: 68, stkAcc: 64, power: 78, stkDef: 56, kicks: 58, clinch: 70,
      tdOff: 84, tdDef: 62, chain: 82, top: 78, bottom: 54, gnp: 80,
      subOff: 58, subDef: 56, back: 56,
      cardio: 66, chin: 52, speed: 76, explode: 86, strength: 78,
      iq: 60, composure: 52, killer: 76, pace: 76,
    },
    flags: { pressureWrestler: true, oneHitter: true },
    notes: "Physical freak with a glass narrative that is partly earned. If the wrestling sticks he's a problem. If it doesn't, the chin is a live wire.",
  }),
  make({
    id: "azamat-murzakanov",
    first: "Azamat",
    last: "Murzakanov",
    division: "light-heavyweight",
    stance: "southpaw",
    heightIn: 70,
    reachIn: 71,
    age: 37,
    country: "Russia",
    w: 16,
    l: 1,
    ranking: 8,
    koWins: 12,
    subWins: 0,
    ratings: {
      stkOut: 70, stkAcc: 72, power: 86, stkDef: 66, kicks: 74, clinch: 64,
      tdOff: 58, tdDef: 64, chain: 54, top: 58, bottom: 50, gnp: 70,
      subOff: 40, subDef: 58, back: 42,
      cardio: 64, chin: 68, speed: 66, explode: 74, strength: 78,
      iq: 64, composure: 66, killer: 82, pace: 66,
    },
    flags: { oneHitter: true },
  }),
  make({
    id: "dominick-reyes",
    first: "Dominick",
    last: "Reyes",
    nickname: "The Devastator",
    division: "light-heavyweight",
    stance: "southpaw",
    heightIn: 76,
    reachIn: 77,
    age: 36,
    country: "USA",
    w: 16,
    l: 5,
    ranking: 10,
    koWins: 9,
    subWins: 2,
    koLosses: 4,
    ratings: {
      stkOut: 70, stkAcc: 66, power: 78, stkDef: 58, kicks: 68, clinch: 54,
      tdOff: 50, tdDef: 56, chain: 46, top: 50, bottom: 48, gnp: 58,
      subOff: 44, subDef: 52, back: 44,
      cardio: 62, chin: 50, speed: 70, explode: 72, strength: 70,
      iq: 60, composure: 52, killer: 70, pace: 68,
    },
    flags: { oneHitter: true },
    notes: "The Jones/Blachowicz chin questions never left. Power is still there. Durability is the bet you're making.",
  }),
  make({
    id: "nikita-krylov",
    first: "Nikita",
    last: "Krylov",
    nickname: "The Miner",
    division: "light-heavyweight",
    heightIn: 75,
    reachIn: 77.5,
    age: 34,
    country: "Ukraine",
    w: 31,
    l: 12,
    ranking: 15,
    koWins: 11,
    subWins: 16,
    koLosses: 4,
    subLosses: 4,
    ratings: {
      stkOut: 66, stkAcc: 60, power: 70, stkDef: 54, kicks: 62, clinch: 66,
      tdOff: 62, tdDef: 54, chain: 60, top: 64, bottom: 58, gnp: 66,
      subOff: 78, subDef: 58, back: 72,
      cardio: 62, chin: 56, speed: 62, explode: 64, strength: 72,
      iq: 58, composure: 52, killer: 74, pace: 68,
    },
  }),
  make({
    id: "abdul-rakhman-yakhyaev",
    first: "Abdul-Rakhman",
    last: "Yakhyaev",
    division: "light-heavyweight",
    heightIn: 73,
    reachIn: 75,
    age: 28,
    country: "Russia",
    w: 10,
    l: 0,
    koWins: 6,
    subWins: 2,
    ratings: {
      stkOut: 66, stkAcc: 64, power: 72, stkDef: 60, kicks: 60, clinch: 58,
      tdOff: 64, tdDef: 62, chain: 62, top: 64, bottom: 54, gnp: 66,
      subOff: 56, subDef: 58, back: 54,
      cardio: 66, chin: 64, speed: 64, explode: 68, strength: 72,
      iq: 58, composure: 58, killer: 66, pace: 66,
    },
  }),
  make({
    id: "abus-magomedov",
    first: "Abusupiyan",
    last: "Magomedov",
    nickname: "Abus",
    division: "middleweight",
    heightIn: 74,
    reachIn: 76,
    age: 36,
    country: "Germany",
    w: 29,
    l: 7,
    d: 1,
    ranking: 12,
    koWins: 14,
    subWins: 8,
    koLosses: 3,
    ratings: {
      stkOut: 68, stkAcc: 70, power: 80, stkDef: 60, kicks: 72, clinch: 58,
      tdOff: 50, tdDef: 56, chain: 48, top: 54, bottom: 50, gnp: 62,
      subOff: 64, subDef: 58, back: 58,
      cardio: 60, chin: 58, speed: 62, explode: 66, strength: 70,
      iq: 62, composure: 58, killer: 74, pace: 64,
    },
    flags: { oneHitter: true },
  }),
  make({
    id: "cam-rowston",
    first: "Cam",
    last: "Rowston",
    division: "middleweight",
    heightIn: 73,
    reachIn: 75,
    age: 28,
    country: "Australia",
    w: 15,
    l: 3,
    koWins: 7,
    subWins: 4,
    ratings: {
      stkOut: 64, stkAcc: 62, power: 64, stkDef: 60, kicks: 58, clinch: 56,
      tdOff: 60, tdDef: 60, chain: 58, top: 60, bottom: 56, gnp: 60,
      subOff: 58, subDef: 58, back: 56,
      cardio: 66, chin: 62, speed: 64, explode: 64, strength: 64,
      iq: 60, composure: 60, killer: 60, pace: 64,
    },
  }),
  make({
    id: "grant-dawson",
    first: "Grant",
    last: "Dawson",
    nickname: "KGD",
    division: "lightweight",
    heightIn: 70,
    reachIn: 72,
    age: 32,
    country: "USA",
    w: 24,
    l: 3,
    d: 1,
    koWins: 4,
    subWins: 12,
    ratings: {
      stkOut: 60, stkAcc: 62, power: 54, stkDef: 64, kicks: 52, clinch: 72,
      tdOff: 82, tdDef: 70, chain: 84, top: 84, bottom: 70, gnp: 66,
      subOff: 82, subDef: 74, back: 82,
      cardio: 80, chin: 68, speed: 66, explode: 70, strength: 68,
      iq: 76, composure: 74, killer: 70, pace: 74,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "nurullo-aliev",
    first: "Nurullo",
    last: "Aliev",
    division: "lightweight",
    heightIn: 70,
    reachIn: 72,
    age: 27,
    country: "Tajikistan",
    w: 12,
    l: 0,
    koWins: 3,
    subWins: 2,
    ratings: {
      stkOut: 64, stkAcc: 64, power: 56, stkDef: 66, kicks: 54, clinch: 68,
      tdOff: 76, tdDef: 74, chain: 76, top: 76, bottom: 64, gnp: 64,
      subOff: 58, subDef: 68, back: 58,
      cardio: 78, chin: 70, speed: 64, explode: 66, strength: 70,
      iq: 68, composure: 70, killer: 50, pace: 72,
    },
    flags: { pressureWrestler: true, decisionWrestler: true },
  }),
  make({
    id: "brendan-allen",
    first: "Brendan",
    last: "Allen",
    nickname: "All In",
    division: "middleweight",
    heightIn: 74,
    reachIn: 75,
    age: 30,
    country: "USA",
    w: 27,
    l: 7,
    ranking: 4,
    koWins: 7,
    subWins: 14,
    ratings: {
      stkOut: 66, stkAcc: 68, power: 60, stkDef: 64, kicks: 58, clinch: 70,
      tdOff: 74, tdDef: 66, chain: 76, top: 80, bottom: 72, gnp: 68,
      subOff: 86, subDef: 74, back: 84,
      cardio: 76, chin: 66, speed: 62, explode: 64, strength: 68,
      iq: 78, composure: 74, killer: 78, pace: 70,
    },
    flags: { pressureWrestler: true },
    notes: "Submission hunter who wins the second grip. If it stays a kickboxing match for 25 minutes he's uncomfortable.",
  }),
  make({
    id: "christian-leroy-duncan",
    first: "Christian Leroy",
    last: "Duncan",
    nickname: "CLD",
    division: "middleweight",
    stance: "switch",
    heightIn: 74,
    reachIn: 79,
    age: 31,
    country: "England",
    w: 15,
    l: 2,
    ranking: 10,
    koWins: 9,
    subWins: 1,
    ratings: {
      stkOut: 76, stkAcc: 74, power: 74, stkDef: 68, kicks: 76, clinch: 54,
      tdOff: 44, tdDef: 58, chain: 42, top: 50, bottom: 46, gnp: 58,
      subOff: 36, subDef: 52, back: 38,
      cardio: 66, chin: 64, speed: 72, explode: 72, strength: 66,
      iq: 64, composure: 62, killer: 70, pace: 70,
    },
    notes: "Long southpaw/switch kicker. TDD is the entire fight. Hasn't lived in a grappler's fourth round.",
  }),
  make({
    id: "matheus-camilo",
    first: "Matheus",
    last: "Camilo",
    division: "lightweight",
    heightIn: 70,
    reachIn: 72,
    age: 26,
    country: "Brazil",
    w: 11,
    l: 3,
    koWins: 4,
    subWins: 5,
    ratings: {
      stkOut: 64, stkAcc: 62, power: 60, stkDef: 60, kicks: 56, clinch: 64,
      tdOff: 68, tdDef: 62, chain: 68, top: 70, bottom: 64, gnp: 64,
      subOff: 72, subDef: 64, back: 70,
      cardio: 68, chin: 62, speed: 66, explode: 66, strength: 62,
      iq: 64, composure: 62, killer: 66, pace: 68,
    },
  }),
  make({
    id: "jai-herbert",
    first: "Jai",
    last: "Herbert",
    division: "lightweight",
    heightIn: 73,
    reachIn: 75,
    age: 38,
    country: "England",
    w: 14,
    l: 6,
    d: 1,
    koWins: 7,
    subWins: 1,
    koLosses: 3,
    ratings: {
      stkOut: 70, stkAcc: 66, power: 70, stkDef: 60, kicks: 68, clinch: 50,
      tdOff: 40, tdDef: 52, chain: 38, top: 46, bottom: 44, gnp: 54,
      subOff: 36, subDef: 50, back: 36,
      cardio: 62, chin: 56, speed: 64, explode: 60, strength: 60,
      iq: 60, composure: 56, killer: 62, pace: 64,
    },
  }),
  make({
    id: "loopy-godinez",
    first: "Lupita",
    last: "Godinez",
    nickname: "Loopy",
    division: "womens-strawweight",
    heightIn: 62,
    reachIn: 62,
    age: 33,
    country: "Mexico",
    w: 14,
    l: 6,
    ranking: 8,
    koWins: 1,
    subWins: 4,
    ratings: {
      stkOut: 64, stkAcc: 60, power: 48, stkDef: 62, kicks: 52, clinch: 68,
      tdOff: 76, tdDef: 70, chain: 76, top: 76, bottom: 68, gnp: 60,
      subOff: 68, subDef: 68, back: 68,
      cardio: 80, chin: 70, speed: 64, explode: 62, strength: 60,
      iq: 70, composure: 72, killer: 52, pace: 76,
    },
    flags: { pressureWrestler: true, decisionWrestler: true },
  }),
  make({
    id: "ketlen-souza",
    first: "Ketlen",
    last: "Souza",
    division: "womens-strawweight",
    heightIn: 64,
    reachIn: 65,
    age: 29,
    country: "Brazil",
    w: 17,
    l: 6,
    koWins: 6,
    subWins: 4,
    koLosses: 2,
    ratings: {
      stkOut: 70, stkAcc: 66, power: 64, stkDef: 60, kicks: 64, clinch: 54,
      tdOff: 48, tdDef: 56, chain: 46, top: 50, bottom: 50, gnp: 56,
      subOff: 52, subDef: 54, back: 50,
      cardio: 66, chin: 60, speed: 70, explode: 68, strength: 56,
      iq: 60, composure: 58, killer: 64, pace: 70,
    },
  }),
  make({
    id: "andre-fili",
    first: "Andre",
    last: "Fili",
    nickname: "Touchy",
    division: "featherweight",
    heightIn: 71,
    reachIn: 74,
    age: 36,
    country: "USA",
    w: 25,
    l: 14,
    koWins: 10,
    subWins: 4,
    koLosses: 5,
    ratings: {
      stkOut: 72, stkAcc: 60, power: 64, stkDef: 56, kicks: 70, clinch: 52,
      tdOff: 50, tdDef: 54, chain: 48, top: 50, bottom: 50, gnp: 54,
      subOff: 46, subDef: 54, back: 46,
      cardio: 68, chin: 58, speed: 68, explode: 64, strength: 58,
      iq: 62, composure: 56, killer: 58, pace: 72,
    },
  }),
  make({
    id: "kai-kamaka",
    first: "Kai",
    last: "Kamaka III",
    nickname: "The Fighting Hawaiian",
    division: "featherweight",
    heightIn: 67,
    reachIn: 69,
    age: 31,
    country: "USA",
    w: 18,
    l: 8,
    d: 1,
    koWins: 5,
    subWins: 2,
    ratings: {
      stkOut: 70, stkAcc: 62, power: 58, stkDef: 60, kicks: 56, clinch: 60,
      tdOff: 58, tdDef: 60, chain: 56, top: 58, bottom: 56, gnp: 56,
      subOff: 48, subDef: 58, back: 48,
      cardio: 74, chin: 66, speed: 66, explode: 62, strength: 60,
      iq: 64, composure: 66, killer: 52, pace: 74,
    },
  }),
  make({
    id: "julius-walker",
    first: "Julius",
    last: "Walker",
    division: "light-heavyweight",
    heightIn: 75,
    reachIn: 78,
    age: 26,
    country: "USA",
    w: 7,
    l: 3,
    koWins: 5,
    subWins: 1,
    koLosses: 2,
    ratings: {
      stkOut: 66, stkAcc: 62, power: 72, stkDef: 56, kicks: 58, clinch: 54,
      tdOff: 50, tdDef: 52, chain: 46, top: 50, bottom: 46, gnp: 62,
      subOff: 44, subDef: 50, back: 44,
      cardio: 60, chin: 56, speed: 66, explode: 70, strength: 68,
      iq: 52, composure: 50, killer: 66, pace: 66,
    },
  }),
  make({
    id: "gerald-meerschaert",
    first: "Gerald",
    last: "Meerschaert",
    nickname: "GM3",
    division: "light-heavyweight",
    heightIn: 73,
    reachIn: 76,
    age: 38,
    country: "USA",
    w: 37,
    l: 22,
    koWins: 7,
    subWins: 28,
    subLosses: 6,
    ratings: {
      stkOut: 54, stkAcc: 52, power: 50, stkDef: 48, kicks: 44, clinch: 58,
      tdOff: 58, tdDef: 48, chain: 56, top: 64, bottom: 70, gnp: 54,
      subOff: 88, subDef: 64, back: 80,
      cardio: 62, chin: 54, speed: 48, explode: 46, strength: 62,
      iq: 70, composure: 60, killer: 78, pace: 58,
    },
    notes: "Walking submission. Chin and striking defense are the reason he's 22 losses. Always live on the mat, never safe standing.",
  }),
  make({
    id: "malcolm-wellmaker",
    first: "Malcolm",
    last: "Wellmaker",
    division: "bantamweight",
    heightIn: 67,
    reachIn: 69,
    age: 27,
    country: "USA",
    w: 10,
    l: 2,
    koWins: 7,
    subWins: 1,
    ratings: {
      stkOut: 72, stkAcc: 68, power: 76, stkDef: 62, kicks: 64, clinch: 54,
      tdOff: 46, tdDef: 58, chain: 44, top: 50, bottom: 46, gnp: 60,
      subOff: 42, subDef: 54, back: 42,
      cardio: 66, chin: 62, speed: 72, explode: 74, strength: 60,
      iq: 58, composure: 56, killer: 72, pace: 70,
    },
    flags: { oneHitter: true },
  }),
  make({
    id: "otari-tanzilovi",
    first: "Otari",
    last: "Tanzilovi",
    division: "bantamweight",
    heightIn: 66,
    reachIn: 67,
    age: 29,
    country: "Georgia",
    w: 10,
    l: 2,
    koWins: 4,
    subWins: 3,
    ratings: {
      stkOut: 62, stkAcc: 62, power: 60, stkDef: 62, kicks: 54, clinch: 64,
      tdOff: 70, tdDef: 66, chain: 70, top: 70, bottom: 62, gnp: 64,
      subOff: 64, subDef: 62, back: 64,
      cardio: 70, chin: 64, speed: 64, explode: 66, strength: 66,
      iq: 62, composure: 62, killer: 60, pace: 68,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "ismael-bonfim",
    first: "Ismael",
    last: "Bonfim",
    division: "lightweight",
    heightIn: 70,
    reachIn: 72,
    age: 30,
    country: "Brazil",
    w: 20,
    l: 7,
    koWins: 12,
    subWins: 2,
    koLosses: 3,
    ratings: {
      stkOut: 74, stkAcc: 68, power: 74, stkDef: 60, kicks: 70, clinch: 54,
      tdOff: 46, tdDef: 56, chain: 44, top: 50, bottom: 48, gnp: 58,
      subOff: 44, subDef: 54, back: 44,
      cardio: 66, chin: 58, speed: 74, explode: 72, strength: 60,
      iq: 60, composure: 56, killer: 70, pace: 72,
    },
  }),
  make({
    id: "francisco-prado",
    first: "Francisco",
    last: "Prado",
    division: "lightweight",
    heightIn: 70,
    reachIn: 73,
    age: 29,
    country: "Argentina",
    w: 12,
    l: 5,
    koWins: 5,
    subWins: 4,
    ratings: {
      stkOut: 64, stkAcc: 62, power: 62, stkDef: 58, kicks: 58, clinch: 56,
      tdOff: 58, tdDef: 56, chain: 56, top: 58, bottom: 54, gnp: 58,
      subOff: 60, subDef: 56, back: 56,
      cardio: 64, chin: 58, speed: 64, explode: 62, strength: 60,
      iq: 58, composure: 56, killer: 60, pace: 64,
    },
  }),
  make({
    id: "joaquin-buckley",
    first: "Joaquin",
    last: "Buckley",
    nickname: "New Mansa",
    division: "welterweight",
    heightIn: 70,
    reachIn: 76,
    age: 32,
    country: "USA",
    w: 21,
    l: 8,
    ranking: 10,
    koWins: 14,
    subWins: 0,
    koLosses: 3,
    ratings: {
      stkOut: 70, stkAcc: 64, power: 84, stkDef: 58, kicks: 78, clinch: 56,
      tdOff: 44, tdDef: 56, chain: 42, top: 48, bottom: 46, gnp: 62,
      subOff: 34, subDef: 52, back: 36,
      cardio: 68, chin: 62, speed: 76, explode: 82, strength: 70,
      iq: 60, composure: 58, killer: 80, pace: 74,
    },
    flags: { oneHitter: true },
  }),
  make({
    id: "mike-malott",
    first: "Mike",
    last: "Malott",
    nickname: "Proper",
    division: "welterweight",
    heightIn: 73,
    reachIn: 74,
    age: 34,
    country: "Canada",
    w: 14,
    l: 2,
    d: 1,
    ranking: 13,
    koWins: 6,
    subWins: 6,
    ratings: {
      stkOut: 66, stkAcc: 66, power: 70, stkDef: 62, kicks: 60, clinch: 64,
      tdOff: 70, tdDef: 64, chain: 68, top: 72, bottom: 62, gnp: 70,
      subOff: 74, subDef: 64, back: 70,
      cardio: 70, chin: 64, speed: 64, explode: 68, strength: 70,
      iq: 68, composure: 66, killer: 74, pace: 68,
    },
  }),
  make({
    id: "renato-moicano",
    first: "Renato",
    last: "Moicano",
    division: "lightweight",
    heightIn: 71,
    reachIn: 72,
    age: 37,
    country: "Brazil",
    w: 21,
    l: 7,
    d: 1,
    ranking: 12,
    koWins: 2,
    subWins: 9,
    koLosses: 3,
    ratings: {
      stkOut: 70, stkAcc: 68, power: 58, stkDef: 66, kicks: 64, clinch: 62,
      tdOff: 64, tdDef: 68, chain: 64, top: 72, bottom: 74, gnp: 62,
      subOff: 82, subDef: 74, back: 78,
      cardio: 70, chin: 58, speed: 66, explode: 62, strength: 62,
      iq: 80, composure: 70, killer: 70, pace: 70,
    },
  }),
  make({
    id: "tom-nolan",
    first: "Tom",
    last: "Nolan",
    division: "lightweight",
    heightIn: 75,
    reachIn: 76,
    age: 26,
    country: "Australia",
    w: 11,
    l: 1,
    ranking: 14,
    koWins: 8,
    subWins: 1,
    ratings: {
      stkOut: 74, stkAcc: 70, power: 76, stkDef: 64, kicks: 72, clinch: 52,
      tdOff: 42, tdDef: 56, chain: 40, top: 48, bottom: 44, gnp: 58,
      subOff: 40, subDef: 52, back: 40,
      cardio: 66, chin: 62, speed: 70, explode: 72, strength: 64,
      iq: 58, composure: 56, killer: 72, pace: 70,
    },
  }),
  make({
    id: "gabriel-bonfim",
    first: "Gabriel",
    last: "Bonfim",
    nickname: "Marretinha",
    division: "welterweight",
    heightIn: 73,
    reachIn: 76,
    age: 28,
    country: "Brazil",
    w: 20,
    l: 1,
    ranking: 5,
    koWins: 5,
    subWins: 13,
    ratings: {
      stkOut: 66, stkAcc: 66, power: 62, stkDef: 64, kicks: 58, clinch: 70,
      tdOff: 78, tdDef: 70, chain: 80, top: 82, bottom: 70, gnp: 70,
      subOff: 88, subDef: 76, back: 86,
      cardio: 76, chin: 66, speed: 68, explode: 72, strength: 70,
      iq: 74, composure: 72, killer: 82, pace: 74,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "sean-brady",
    first: "Sean",
    last: "Brady",
    division: "welterweight",
    heightIn: 70,
    reachIn: 72,
    age: 33,
    country: "USA",
    w: 19,
    l: 2,
    ranking: 6,
    koWins: 3,
    subWins: 7,
    koLosses: 2,
    ratings: {
      stkOut: 64, stkAcc: 68, power: 56, stkDef: 68, kicks: 54, clinch: 74,
      tdOff: 84, tdDef: 74, chain: 86, top: 86, bottom: 68, gnp: 68,
      subOff: 76, subDef: 74, back: 74,
      cardio: 78, chin: 64, speed: 62, explode: 64, strength: 72,
      iq: 80, composure: 76, killer: 66, pace: 72,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "ciryl-gane",
    first: "Ciryl",
    last: "Gane",
    nickname: "Bon Gamin",
    division: "heavyweight",
    heightIn: 77,
    reachIn: 81,
    age: 36,
    country: "France",
    w: 14,
    l: 2,
    ranking: "C",
    koWins: 7,
    subWins: 0,
    subLosses: 1,
    ratings: {
      stkOut: 82, stkAcc: 76, power: 72, stkDef: 78, kicks: 84, clinch: 60,
      tdOff: 36, tdDef: 58, chain: 34, top: 42, bottom: 40, gnp: 54,
      subOff: 28, subDef: 46, back: 30,
      cardio: 78, chin: 70, speed: 74, explode: 68, strength: 70,
      iq: 76, composure: 70, killer: 64, pace: 72,
    },
    notes: "Best mover at heavyweight. Wrestling defense is the scar from Ngannou/Jones nights. Hokit is built to grab that scar.",
  }),
  make({
    id: "josh-hokit",
    first: "Josh",
    last: "Hokit",
    division: "heavyweight",
    heightIn: 73,
    reachIn: 76,
    age: 29,
    country: "USA",
    w: 10,
    l: 0,
    ranking: 4,
    koWins: 4,
    subWins: 4,
    ratings: {
      stkOut: 56, stkAcc: 58, power: 64, stkDef: 54, kicks: 44, clinch: 70,
      tdOff: 86, tdDef: 72, chain: 84, top: 82, bottom: 60, gnp: 76,
      subOff: 68, subDef: 64, back: 66,
      cardio: 70, chin: 68, speed: 58, explode: 72, strength: 86,
      iq: 64, composure: 66, killer: 68, pace: 68,
    },
    flags: { pressureWrestler: true },
    notes: "Ex-football wrestler, undefeated. Path is ugly and correct: chain, ride, gnP. Five rounds with Gane's kicking is the tax.",
  }),
  make({
    id: "islam-makhachev",
    first: "Islam",
    last: "Makhachev",
    division: "lightweight",
    heightIn: 70,
    reachIn: 70.5,
    age: 35,
    country: "Russia",
    w: 27,
    l: 1,
    ranking: "C",
    koWins: 5,
    subWins: 13,
    ratings: {
      stkOut: 78, stkAcc: 76, power: 70, stkDef: 80, kicks: 72, clinch: 88,
      tdOff: 92, tdDef: 90, chain: 94, top: 94, bottom: 78, gnp: 80,
      subOff: 90, subDef: 88, back: 90,
      cardio: 88, chin: 80, speed: 74, explode: 78, strength: 82,
      iq: 94, composure: 92, killer: 82, pace: 76,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "ilia-topuria",
    first: "Ilia",
    last: "Topuria",
    nickname: "El Matador",
    division: "lightweight",
    heightIn: 67,
    reachIn: 69,
    age: 29,
    country: "Spain",
    w: 16,
    l: 0,
    koWins: 11,
    subWins: 4,
    ratings: {
      stkOut: 80, stkAcc: 82, power: 94, stkDef: 78, kicks: 64, clinch: 74,
      tdOff: 78, tdDef: 84, chain: 76, top: 80, bottom: 74, gnp: 82,
      subOff: 80, subDef: 80, back: 78,
      cardio: 80, chin: 78, speed: 82, explode: 88, strength: 84,
      iq: 84, composure: 86, killer: 96, pace: 76,
    },
    flags: { oneHitter: true },
  }),
  make({
    id: "tom-aspinall",
    first: "Tom",
    last: "Aspinall",
    division: "heavyweight",
    heightIn: 77,
    reachIn: 78,
    age: 33,
    country: "England",
    w: 15,
    l: 3,
    koWins: 12,
    subWins: 2,
    koLosses: 1,
    ratings: {
      stkOut: 78, stkAcc: 74, power: 88, stkDef: 70, kicks: 70, clinch: 64,
      tdOff: 72, tdDef: 70, chain: 70, top: 74, bottom: 62, gnp: 80,
      subOff: 70, subDef: 68, back: 66,
      cardio: 74, chin: 64, speed: 82, explode: 88, strength: 80,
      iq: 76, composure: 74, killer: 90, pace: 80,
    },
    flags: { oneHitter: true },
  }),
  make({
    id: "alex-pereira",
    first: "Alex",
    last: "Pereira",
    nickname: "Poatan",
    division: "light-heavyweight",
    stance: "orthodox",
    heightIn: 76,
    reachIn: 79,
    age: 39,
    country: "Brazil",
    w: 13,
    l: 3,
    koWins: 10,
    subWins: 0,
    koLosses: 1,
    subLosses: 1,
    ratings: {
      stkOut: 74, stkAcc: 78, power: 96, stkDef: 70, kicks: 88, clinch: 62,
      tdOff: 32, tdDef: 54, chain: 30, top: 40, bottom: 36, gnp: 58,
      subOff: 24, subDef: 48, back: 28,
      cardio: 66, chin: 72, speed: 66, explode: 70, strength: 80,
      iq: 74, composure: 80, killer: 94, pace: 64,
    },
    flags: { oneHitter: true, bodyAttacker: true },
  }),
  make({
    id: "max-holloway",
    first: "Max",
    last: "Holloway",
    nickname: "Blessed",
    division: "lightweight",
    heightIn: 71,
    reachIn: 69.5,
    age: 34,
    country: "USA",
    w: 27,
    l: 8,
    koWins: 12,
    subWins: 2,
    koLosses: 2,
    ratings: {
      stkOut: 96, stkAcc: 72, power: 68, stkDef: 74, kicks: 72, clinch: 64,
      tdOff: 50, tdDef: 78, chain: 48, top: 58, bottom: 66, gnp: 70,
      subOff: 52, subDef: 70, back: 50,
      cardio: 94, chin: 86, speed: 80, explode: 72, strength: 62,
      iq: 90, composure: 92, killer: 80, pace: 96,
    },
  }),
  make({
    id: "arman-tsarukyan",
    first: "Arman",
    last: "Tsarukyan",
    nickname: "Ahalkalakets",
    division: "lightweight",
    heightIn: 67,
    reachIn: 72,
    age: 30,
    country: "Armenia",
    w: 23,
    l: 3,
    koWins: 9,
    subWins: 5,
    ratings: {
      stkOut: 78, stkAcc: 72, power: 74, stkDef: 72, kicks: 68, clinch: 80,
      tdOff: 86, tdDef: 80, chain: 86, top: 82, bottom: 70, gnp: 78,
      subOff: 68, subDef: 74, back: 68,
      cardio: 82, chin: 74, speed: 78, explode: 82, strength: 80,
      iq: 78, composure: 74, killer: 76, pace: 82,
    },
    flags: { pressureWrestler: true },
  }),
  make({
    id: "alexandre-pantoja",
    first: "Alexandre",
    last: "Pantoja",
    nickname: "The Cannibal",
    division: "flyweight",
    heightIn: 65,
    reachIn: 67,
    age: 36,
    country: "Brazil",
    w: 29,
    l: 6,
    ranking: "C",
    koWins: 8,
    subWins: 11,
    ratings: {
      stkOut: 76, stkAcc: 70, power: 68, stkDef: 72, kicks: 64, clinch: 78,
      tdOff: 80, tdDef: 74, chain: 82, top: 84, bottom: 80, gnp: 78,
      subOff: 88, subDef: 80, back: 86,
      cardio: 86, chin: 74, speed: 76, explode: 78, strength: 70,
      iq: 88, composure: 86, killer: 84, pace: 84,
    },
  }),
  make({
    id: "joshua-van",
    first: "Joshua",
    last: "Van",
    division: "flyweight",
    heightIn: 65,
    reachIn: 66,
    age: 25,
    country: "Myanmar",
    w: 16,
    l: 2,
    koWins: 6,
    subWins: 1,
    ratings: {
      stkOut: 88, stkAcc: 76, power: 70, stkDef: 68, kicks: 66, clinch: 60,
      tdOff: 48, tdDef: 64, chain: 46, top: 52, bottom: 50, gnp: 60,
      subOff: 42, subDef: 58, back: 44,
      cardio: 82, chin: 66, speed: 84, explode: 80, strength: 58,
      iq: 70, composure: 68, killer: 72, pace: 90,
    },
  }),
  make({
    id: "valentina-shevchenko",
    first: "Valentina",
    last: "Shevchenko",
    nickname: "Bullet",
    division: "womens-flyweight",
    stance: "southpaw",
    heightIn: 65,
    reachIn: 66.5,
    age: 38,
    country: "Kyrgyzstan",
    w: 25,
    l: 5,
    d: 1,
    koWins: 8,
    subWins: 4,
    ratings: {
      stkOut: 80, stkAcc: 84, power: 74, stkDef: 86, kicks: 90, clinch: 82,
      tdOff: 70, tdDef: 82, chain: 68, top: 80, bottom: 72, gnp: 72,
      subOff: 70, subDef: 80, back: 66,
      cardio: 80, chin: 76, speed: 74, explode: 70, strength: 70,
      iq: 94, composure: 92, killer: 74, pace: 70,
    },
    flags: { southpawKicker: true },
  }),
];

export const FIGHTER_BY_ID: Record<string, Fighter> = Object.fromEntries(
  FIGHTERS.map((f) => [f.id, f]),
);

export function fighterById(id: string): Fighter {
  const f = FIGHTER_BY_ID[id];
  if (!f) throw new Error(`Unknown fighter: ${id}`);
  return f;
}

export function displayName(f: Fighter): string {
  return `${f.first} ${f.last}`;
}

export function recordString(f: Fighter): string {
  return f.record.d ? `${f.record.w}-${f.record.l}-${f.record.d}` : `${f.record.w}-${f.record.l}`;
}

export function searchFighters(q: string): Fighter[] {
  const s = q.trim().toLowerCase();
  if (!s) return FIGHTERS;
  return FIGHTERS.filter((f) => {
    const blob = `${f.first} ${f.last} ${f.nickname ?? ""} ${f.country}`.toLowerCase();
    return blob.includes(s);
  });
}
