import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/model")({ component: ModelPage });

function ModelPage() {
  return (
    <article className="max-w-2xl space-y-6">
      <h1 className="font-display text-4xl font-semibold">How the desk thinks</h1>
      <p className="text-sm text-muted leading-relaxed">
        CAGECASH is not a poll of analysts and it is not a copy of the last five Twitter posts. Every number on this
        desk comes from a fight-level Monte Carlo: 15-second ticks, stance and reach, wrestling chains, accumulated
        damage, cardio fade, altitude, age, and three noisy judges.
      </p>
      <section className="space-y-3">
        <h2 className="font-display text-2xl">What gets simulated</h2>
        <ul className="space-y-2 text-sm text-muted">
          <li>Standup exchanges with volume, accuracy, power shots, kicks, calf/body drain.</li>
          <li>Takedown attempts that scale with losing the striking, being behind on cards, and chain-wrestling skill.</li>
          <li>Clinch dirty boxing, trips, and fence work.</li>
          <li>Ground: position ladder, GNP stoppages, submission attempts from back/mount/guard.</li>
          <li>Knockdown and KO hazards that rise with accumulated damage — flash KO tails for one-hitters.</li>
          <li>Stamina drain that punishes pace, wrestling defense, and altitude. Round 4 is a different sport.</li>
          <li>Independent judges with 10–8 thresholds and split-decision noise.</li>
        </ul>
      </section>
      <section className="space-y-3">
        <h2 className="font-display text-2xl">What the book is</h2>
        <p className="text-sm text-muted leading-relaxed">
          Moneylines on numbered cards are a snapshot of listed sportsbook prices (CBS / listed books, 3 Oct 2026).
          Method, round, and total props are generated by a deliberately dumber sportsbook model: career finish mix +
          favorite, then juice. That is the point. Real books do something in that neighborhood. The cage model is
          finer. Edges are the disagreement.
        </p>
      </section>
      <section className="space-y-3">
        <h2 className="font-display text-2xl">How we size</h2>
        <p className="text-sm text-muted leading-relaxed">
          Quarter Kelly by default, hard-capped at 5% of bankroll. MMA variance eats full Kelly for breakfast. A plus-EV
          dog at +500 with a 22% model is a small seat, not a mortgage. Passing is a position.
        </p>
      </section>
      <section className="space-y-3">
        <h2 className="font-display text-2xl">What this is not</h2>
        <p className="text-sm text-muted leading-relaxed">
          Not a sportsbook. Not advice. Ratings are 2026 form estimates, not scraped UFCStats dumps. If a fighter just
          changed overnight, the desk will be late. Re-run the lab, don't worship a number.
        </p>
      </section>
    </article>
  );
}
