/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ModelRouteImport } from './routes/model'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as FightFightIdRouteImport } from './routes/fight.$fightId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const FightFightIdRoute = FightFightIdRouteImport.update({
  id: '/fight/$fightId',
  path: '/fight/$fightId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/model': typeof ModelRoute
  '/scanner': typeof ScannerRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/fight/$fightId': typeof FightFightIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/model': typeof ModelRoute
  '/scanner': typeof ScannerRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/fight/$fightId': typeof FightFightIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/model': typeof ModelRoute
  '/scanner': typeof ScannerRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/fight/$fightId': typeof FightFightIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/lab' | '/model' | '/scanner' | '/event/$eventId' | '/fight/$fightId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/lab' | '/model' | '/scanner' | '/event/$eventId' | '/fight/$fightId'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/model'
    | '/scanner'
    | '/event/$eventId'
    | '/fight/$fightId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRoute
  ModelRoute: typeof ModelRoute
  ScannerRoute: typeof ScannerRoute
  EventEventIdRoute: typeof EventEventIdRoute
  FightFightIdRoute: typeof FightFightIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fight/$fightId': {
      id: '/fight/$fightId'
      path: '/fight/$fightId'
      fullPath: '/fight/$fightId'
      preLoaderRoute: typeof FightFightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRoute,
  ModelRoute: ModelRoute,
  ScannerRoute: ScannerRoute,
  EventEventIdRoute: EventEventIdRoute,
  FightFightIdRoute: FightFightIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
